/**
 * @author
 * @version
 */

package hw3;

/**
 * A Tracker stores information about a particular tile in the Picture,
 * including where it was when the puzzle began, and where it should be in the
 * unmodified form of the target picture.
 */
public class Tracker {
	
	private int mixedI;
	private int mixedJ;
	private int correctI;
	private int correctJ;
	private int rotations;
	private boolean isFlipped;
    /**
     * Constructs a Tracker for a tile which belongs at coordinates correct*
     * but begins the puzzle (in the scrambled state) at coordinates mixed*
     * The current orientation of the corresponding tile is described by the
     * number of rotations (the N in the CN or CNF) and whether it has been
     * hflipped.  If there has been an hflip required to get to the current
     * orientation, then the isFlipped parameter is true.
     *
     * @param mixedI is row number at the start of the puzzle
     * @param mixedJ is column number at the start of the puzzle
     * @param correctI is row number in the solved puzzle
     * @param correctJ is column number in the solved puzzle
     * @param rotations is the number of clockwise rotations as of now
     * @param isFlipped is whether the tile is currently top-face-down
     */
    public Tracker(int mixedI, int mixedJ, int correctI, int correctJ, int rotations, boolean isFlipped) {
    	this.mixedI = mixedI;
    	this.mixedJ = mixedJ;
    	this.correctI = correctI;
    	this.correctJ = correctJ;
    	this.rotations = rotations;
    	this.isFlipped = isFlipped;
    }

    /**
     * Constructs a Tracker whose internal state is described in the
     * fromString parameter, which is obtained by calling toString method
     * below or being in a format that could have been generated by toString
     * below.
     *
     * @see Tracker#toString
     * @param fromString describes the internal state to be constructed
     */
    public Tracker(String fromString) {
    }

    /**
     * Record that the user has rotated the corresponding tile in the Picture
     * clockwise.
     */
    public void clockwise() {
    	rotations++;
    }

    /**
     * Record that the user has rotated the corresponding tile in the Picture
     * anticlockwise.
     */
    public void anticlockwise() {
    	rotations --;
    }

    /**
     * Record that the user has performed an hflip on the corresponding tile
     * in the Picture.  The CN / CNF representation that we are remembering
     * is correspondingly changed.
     */
    public void hflip() {
    	isFlipped = !isFlipped;
    }

    /**
     * Record that the user has performed an vflip on the corresponding tile
     * in the Picture.  The CN / CNF representation that we are remembering
     * is correspondingly changed.
     */
    public void vflip() {
    	this.clockwise();
    	this.clockwise();
    	this.hflip();
    }

    /**
     * Record that the user has transposed the corresponding tile in the
     * Picture.  The CN / CNF representation that we are remembering
     * is correspondingly changed.
     */
    public void transpose() {
    	this.anticlockwise();
    	this.vflip();
    }
    
    /**
     * Get the original row number of the corresponding tile in the scrambled
     * version of the puzzle.
     *
     * @return the row number in scrambled puzzle.
     */
    public int getMixedI() {
    	return mixedI;
    }

    /**
     * Get the original column number of the corresponding tile in the
     * scrambled version of the puzzle.
     *
     * @return the column number in scrambled puzzle.
     */
    public int getMixedJ() {
    	return mixedJ;
    }

    /**
     * Get the final row number of the corresponding tile in the solved
     * version of the puzzle.
     *
     * @return the row number in solved puzzle.
     */
    public int getCorrectI() {
    	return correctI;
    }

    /**
     * Get the final column number of the corresponding tile in the solved
     * version of the puzzle.
     *
     * @return the column number in solved puzzle.
     */
    public int getCorrectJ() {
    	return correctJ;
    }

    /**
     * Gets the number of rotations that should be applied to a solved version
     * of the corresponding tile before placing the corresponding tile into
     * the current state of the puzzle.
     *
     * @return the number of rotations
     */
    public int getRotations() {
    	return rotations;
    }

    /**
     * Gets whether the corresponding tile must be turned top-face-down when
     * placing it into the current state of the puzzle.
     *
     * @return true if the tile must be turned upside down.
     */
    public boolean getIsFlipped() {
    	return isFlipped;
    }

    /**
     * Represents the state of this Tracker as a string, which allows an
     * identical Tracker to be reconstructed later from the string.
     *
     * The format lists the values of the following variables in this order:
     * mixedI, mixedJ, correctI, correctJ, rotations and isFlipped (which were
     * or could have been parameters to the other constructor, to construct
     * this object).  The format separates the values with spaces and does not
     * include any newlines.  The word "true" is used for a true boolean and
     * "false" for a false boolean.
     * 
     * @return the string representation of the tracker.
     */
    public String toString() {
    	return ("" + mixedI + " " + mixedJ + " " + correctI + " " + correctJ + " " + rotations + " " + isFlipped);
    }
}
